# fly.toml app configuration file generated for winter-frog-2922 on 2023-06-25T19:55:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "winter-frog-2922"
primary_region = "ewr"

[env]
PORT = 3006


[http_service]
  internal_port = 3006
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
